//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHostedMediaCallingBot.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceHostedMediaCallingBot.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;established&quot;,
        ///                &quot;directi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CallEstablished {
            get {
                return ResourceManager.GetString("CallEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;established&quot;,
        ///                &quot;mediaSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CallEstablishedWithAudio {
            get {
                return ResourceManager.GetString("CallEstablishedWithAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;establishing&quot;,
        ///                &quot;callCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CallEstablishing {
            get {
                return ResourceManager.GetString("CallEstablishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/631f6000-766a-4c6f-9da3-8755ebe44d19/participants&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/631f6000-766a-4c6f-9da3-8755ebe44d19/participants&quot;,
        ///            &quot;resourceData&quot;: [
        ///                {
        ///                    &quot;@odata.type&quot;: &quot;#microsoft.graph.participant&quot;,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupCallBotJoin {
            get {
                return ResourceManager.GetString("GroupCallBotJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///      {
        ///        &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///        &quot;changeType&quot;: &quot;deleted&quot;,
        ///        &quot;resource&quot;: &quot;/app/calls/631f6000-766a-4c6f-9da3-8755ebe44d19&quot;,
        ///        &quot;resourceUrl&quot;: &quot;/communications/calls/631f6000-766a-4c6f-9da3-8755ebe44d19&quot;,
        ///        &quot;resourceData&quot;: {
        ///          &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///          &quot;state&quot;: &quot;terminated&quot;,
        ///          &quot;resultInfo&quot;: {
        ///            &quot;@odata.type&quot;: &quot;#mic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupCallEnd {
            get {
                return ResourceManager.GetString("GroupCallEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/631f6000-766a-4c6f-9da3-8755ebe44d19&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/631f6000-766a-4c6f-9da3-8755ebe44d19&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;established&quot;,
        ///                &quot;directi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupCallEstablished {
            get {
                return ResourceManager.GetString("GroupCallEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/631f6000-766a-4c6f-9da3-8755ebe44d19&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/631f6000-766a-4c6f-9da3-8755ebe44d19&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;establishing&quot;,
        ///                &quot;callCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupCallEstablishing {
            get {
                return ResourceManager.GetString("GroupCallEstablishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/631f6000-766a-4c6f-9da3-8755ebe44d19/participants&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/631f6000-766a-4c6f-9da3-8755ebe44d19/participants&quot;,
        ///            &quot;resourceData&quot;: [
        ///                {
        ///                    &quot;@odata.type&quot;: &quot;#microsoft.graph.participant&quot;,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupCallUserJoin {
            get {
                return ResourceManager.GetString("GroupCallUserJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;deleted&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;terminated&quot;,
        ///                &quot;resultIn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HangUp {
            get {
                return ResourceManager.GetString("HangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;deleted&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9/operations/11cccef9-7eeb-4910-9189-977c0f0eae85&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9/operations/11cccef9-7eeb-4910-9189-977c0f0eae85&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayPromptFinish {
            get {
                return ResourceManager.GetString("PlayPromptFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotifications&quot;,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;@odata.type&quot;: &quot;#microsoft.graph.commsNotification&quot;,
        ///            &quot;changeType&quot;: &quot;updated&quot;,
        ///            &quot;resource&quot;: &quot;/app/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceUrl&quot;: &quot;/communications/calls/6f1f5c00-8c1b-47f1-be9d-660c501041a9&quot;,
        ///            &quot;resourceData&quot;: {
        ///                &quot;@odata.type&quot;: &quot;#microsoft.graph.call&quot;,
        ///                &quot;state&quot;: &quot;established&quot;,
        ///                &quot;toneInf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TonePress {
            get {
                return ResourceManager.GetString("TonePress", resourceCulture);
            }
        }
    }
}
